# This is the configuration file for
# nin0-bot. If you need any help on
# config you can go to https://bot.nin0dev.com/docs.

# GUILD ID: The bot can only run on ONE server. Specify the ID of that server under that comment.
guild_id: 1188310225309147226
mod:
  dm_on_punish: true # If nin0-bot should DM the user on punish.
  # Variables:
  #    Server info:
  #         [guild.name] for server name
  #         [guild.id] for server ID
  #    Author info:
  #         [author.username] for author username
  #         [author.id] for author ID
  #         [author.mention] for author mention (may only show ID)
  #    Punishment info:
  #         [punishment.reason] for the punish reason
  #         [punishment.expiresin] for expiration timestamp (relative) (only mutes and bans)
  # Please use \n for new lines.
  dm_punish_messages:
    warn: "You have been warned in [guild.name].\n> **Reason:** [punishment.reason]\n> **Author:** [author.username] ([author.mention])"
    mute: "You have been muted in [guild.name].\n> **Reason:** [punishment.reason]\n> **Expires:** [punishment.expiresin]\n> **Author:** [author.username] ([author.mention])"
    unmute: "You have been unmuted from [guild.name].\n> **Reason:** [punishment.reason]\n> **Author:** [author.username] ([author.mention])"
    kick: "You have been kicked from [guild.name].\n> **Reason:** [punishment.reason]\n> **Author:** [author.username] ([author.mention])"
    ban: "You have been banned from [guild.name].\n> **Reason:** [punishment.reason]\n> **Expires:** [punishment.expiresin]\n> **Author:** [author.username] ([author.mention])"
  hide_command_author: false # Will delete the command message (if prefixed) and will make the command response ephemeral (if slash)
  ban_msgdelete_days: 0 # How many days of messages to delete when banning (by default)
  
